version: "3.8"

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zyst3was
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./hotel-app/backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hotel
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Zyst3was

  frontend:
    build: ./hotel-app/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  terraform:
    image: hashicorp/terraform:1.6.0
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins-hotel
    ports:
      - "40002:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
    depends_on:
      - docker-agent

  docker-agent:
    image: docker:24.0.7-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=""
    ports:
      - "2375:2375"

volumes:
  db_data:
  jenkins_home:

