version: '3.8'

services:
  jenkins:
    container_name: jenkins-hotel
    build:
      context: ./jenkins
    ports:
      - "8080:8080"       # UI Jenkins
      - "50000:50000"     # Conexión de agentes
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
    volumes:
      - jenkins_data:/var/jenkins_home
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml
    networks:
      - jenkins-net
    depends_on:
      - docker-agent

  docker-agent:
    image: docker:24.0.7-dind
    container_name: docker-agent
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=""
    networks:
      - jenkins-net
    ports:
      - "2375:2375"

volumes:
  jenkins_data:

networks:
  jenkins-net:
    driver: bridge
